### ISSUE TITLE
Missing data/{split}.pages.refined_claim.s1.t1.jsonl in page_reranker.py

### ISSUE THREAD

**Issue by orianna-zzo** [WilliamZR/unifee#1]
Running `python src/re-ranker/page_reranker.py` needs `data/{split}.pages.refined_claim.s1.t1.jsonl` which is not generated by the previous code nor found in the data directory.

**Comment by lanlanabcd** [comment]
Hi, you can replace the line 222 in src/re-ranker/page_reranker.py

`with open("{0}/{1}.pages.refined_claim.s1.t1.jsonl".format(args.data_path, args.split),"r") as f, open("{0}/{1}.pages.refined_claim.s1.t1.{2}.jsonl".format(args.data_path, args.split, args.max_page,args.max_rerank), "w+") as out_file:`

 with

`with open("{0}/{1}.pages.p{2}.jsonl".format(args.data_path, args.split, args.max_page),"r") as f, open("{0}/{1}.pages.p{2}.r{3}.jsonl".format(args.data_path, args.split, args.max_page,args.max_rerank), "w+") as out_file: `

**Comment by lanlanabcd** [comment]
We are checking if there are other bugs remained, and will make a new commit later.

**Comment by orianna-zzo** [comment]
Thanks.
